<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/Final%20Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print("problem 1 ans.")
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)



problem 1 ans.
[[13.]
 [57.]
 [19.]]


In [6]:
print("di ko alam kung anong problema nya pero ginawa ko naman lahat para di siya mag loko pero huli na ang lahat")
print("p.s:Merry Christmas maam no time na po thank you")

di ko alam kung anong problema nya pero ginawa ko naman lahat para di siya mag loko pero huli na ang lahat
p.s:Merry Christmas maam no time na po thank you


In [2]:
import numpy as np
from numpy.linalg import eig
print("problem 3 ans.")
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round(),"\n")
print("The eigenvector/s is/are:\n",v.round())

problem 3 ans.
[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
