<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/Matrix_and_its_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print (A+B)

[[ 1 -3]
 [ 6  4]]


In [9]:
import numpy as np

A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print (A-B)

[[-11   3]
 [  2  -2]]


In [10]:
import numpy as np

B = np.array([[6,-3],[2,3]])
B = np.array([[6,-3],[2,3]])
print (B-B)

[[0 0]
 [0 0]]
