<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python program to inverse

In [20]:
import numpy as np
A = np.array([[1,2,],[4,7]])
invA = (np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [23]:
C = np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [3]:
##Python Program to Inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [6]:
##Python Program to Inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.linalg.inv(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
