<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question1. Create a Python code that displays a square matrix whose length is 5


In [5]:
import numpy as np
a= np.array([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #square matrix length is 5
print(a)

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


Question2.Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [22]:
import numpy as np
b = np.triu([[1,2,3,4,5],[6,7,8,9,25],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,26,24]])#square matrix below the principal diagonal are zero
print(b)

[[ 1  2  3  4  5]
 [ 0  7  8  9 25]
 [ 0  0 12 13 14]
 [ 0  0  0 18 19]
 [ 0  0  0  0 24]]


Question 3. Create a Python code that displays a square matrix which is symmetrical

In [25]:
import numpy as np
symmetric=np.array([[1,2,3],[2,5,6],[3,8,9]])
print(symmetric)# to display the matrix
symmetric=np.transpose(symmetric)# to tranpose the matrix
print(symmetric)


[[1 2 3]
 [2 5 6]
 [3 8 9]]
[[1 2 3]
 [2 5 8]
 [3 6 9]]


Question 4. What is the inverse of matrix C? Show your solution by python coding

In [24]:
import numpy as np

c= np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(c)
c_=np.linalg.inv(c)# to inverse the matrix i use linalg.inv
print(c_)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


uestion 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding

In [21]:
import numpy as np
e= np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(e)
print(round(np.linalg.det(e)))# to determine the matrix

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


Question 6. Find the roots of the linear equations by showing its python codes

In [34]:
import numpy as np
a=np.array([[5,4,1],[10,9,4],[10,13,15]])
inv_c=np.linalg.inv(c)
print(c)
print(inv_c)

b=np.array([[3,4],[8,8],[19.2]])
x=np.dot(inv_c,b)
print(x)

z=np.dot(c,x)
print(z)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


TypeError: ignored