<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/Practical_Lab_Exam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
W = np.array([[1,3],[2,-2],[3,1]])
print("W")
print(W)

X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print("X")
print(X)

Y = np.array([[1,2,0],[0,-1,2]])
print("Y")
print(Y)

Z = np.array([[0,1],[2,3]])
print("Z")
print(Z)




W
[[ 1  3]
 [ 2 -2]
 [ 3  1]]
X
[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
Y
[[ 1  2  0]
 [ 0 -1  2]]
Z
[[0 1]
 [2 3]]


problem1

A


In [49]:
print("WY")
WY = np.dot(W,Y)
print(WY)

WY
[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


B


In [16]:
R = np.add(Z,Z)
R


array([[0, 2],
       [4, 6]])

C

In [17]:
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
S = 3*X
print(S)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


problem 2


A

In [24]:
yw = np.dot(Y,W)
product = np.power(yw,2)
print(product)
print("false \n")

[[25 49]
 [16 16]]
false 



B

In [50]:
R = np.subtract(WY,X)
print(R)
print("true\n")

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
true



C

In [34]:
C = np.dot(Y,W)
R = np.subtract(C,Z^2)
print(R)
print("false")

[[  3 -10]
 [  4   3]]
false
