<a href="https://colab.research.google.com/github/joeusebio/Linear-Algebra-58020/blob/main/PrelimExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question1

In [5]:
import numpy as np

C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question2

In [8]:
import numpy as np

C = np.eye(4)
print(C*2)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question3

In [6]:
import numpy as np

A = np.array([2,7,4])
B = np.array([3,9,8])

A = np.cross(A,B)
print(A)


[20 -4 -3]
